import mysql.connector
from tkinter import *
from tkinter import messagebox as mb
conn = mysql.connector.connect(host='localhost',user='root',passwd='tiger',database='system28')
cur = conn.cursor()
def tk_register():
      window = Tk()
      window.geometry('600x400')
      window.title('Registration Form')
      window.configure(bg='cyan')
      name = StringVar()
      age = StringVar()
      natn = StringVar()
      gender = StringVar()
      mail = StringVar()
      PASS = StringVar()
      phno = StringVar()
      gender.set(' ')
      image = PhotoImage(file='\\\srlab\\tcdata\system28\Documents\Shourya_XII-A\\Un bg.png')
      Label(window,image=image).place(x=0,y=0)
      Label(window,text='Registration Form',bg='black',fg='yellow',font=('Copperplate Gothic Bold',16,'underline')).pack()
      Label(window,text='Name ',font=('Elephant',12),bg='black',fg='yellow').place(x=20,y=65)
      txt1=Entry(window,textvariable = name,width=45,font=12)
      txt1.place(x=130,y=65)
      Label(window,text='Age  ',font=('Elephant',12),bg='black',fg='yellow').place(x=20,y=95)
      txt2=Entry(window,textvariable = age,width=45,font=12)
      txt2.place(x=130,y=95)
      Label(window,text='Nationality  ',font=('Elephant',12),bg='black',fg='yellow').place(x=20,y=125)
      txt3=Entry(window,textvariable = natn,width=45,font=12)
      txt3.place(x=130,y=125)
      Label(window,text='Email  ',font=('Elephant',12),bg='black',fg='yellow').place(x=20,y=155)
      txt4=Entry(window,textvariable = mail,width=45,font=12)
      txt4.place(x=130,y=155)
      Label(window,text='Phone No.  ',font=('Elephant',12),bg='black',fg='yellow').place(x=20,y=185)
      txt5=Entry(window,textvariable = phno,width=45,font=12)
      txt5.place(x=130,y=185)
      Label(window,text='Password  ',font=('Elephant',12),bg='black',fg='yellow').place(x=20,y=215)
      txt6=Entry(window,textvariable = PASS,show='*',width=45,font=12)
      txt6.place(x=130,y=215)
      LabelFrame(window,text = 'Gender',width=550,height=100,font=14,bg='black',fg='yellow').place(x=10,y=245)
      Radiobutton(window,text = 'Male',variable = gender,value='Male',font=('Copperplate Gothic Bold',14),bg='black',fg='yellow').place(x=255,y=265)
      Radiobutton(window,text = 'Female',variable = gender,value='Female',font=('Copperplate Gothic Bold',14),bg='black',fg='yellow').place(x=255,y=305)
      def retrieve():
            NAME=name.get()
            AGE=age.get()
            NATN=natn.get()
            GENDER=gender.get()
            MAIL=mail.get()
            passwd=PASS.get()
            PHNO=phno.get()
            query = 'insert into intrstlr values("{}",{},"{}","{}","{}","{}","{}",NULL)'.format(NAME,int(AGE),GENDER,NATN,MAIL,passwd,PHNO)
            cur.execute(query)
            cur.execute('commit;')
            mb.showinfo('Congratulations','You have been registered')
            window.destroy()

      Button(window,text='Submit',font=('Courier New',12),command=retrieve,width=55).place(x=10,y=350)
      window.mainloop()
      
